### ISSUE TITLE
[BUG]: Slows down vitest

### ISSUE THREAD

**Issue by hmajid2301** [shinokada/svelte-awesome-icons#2]
### Description of the bug

It seems when I use this library with vitest my tests run a lot slower ~14 minutes; 

CI: https://gitlab.com/bookmarkey/gui/-/jobs/3703491548

According to this post; https://github.com/vitest-dev/vitest/issues/1861#issuecomment-1413419837

This seem to be caused by: 

> @hmajid2301 in your case one of the Svelte file imports is unable to tree shake imports. This seems to take most of the time.
> 
> ```ts
> import { FolderSolid } from "svelte-awesome-icons";
> ```
> 
> This ends ups importing all +2000 icons.
> 
> ```js
> const __vite_ssr_import_0__ = await __vite_ssr_import__("/node_modules/.pnpm/svelte-awesome-icons@0.2.11/node_modules/svelte-awesome-icons/PasteSolid.svelte");
> const __vite_ssr_import_1__ = await __vite_ssr_import__("/node_modules/.pnpm/svelte-awesome-icons@0.2.11/node_modules/svelte-awesome-icons/ScrewdriverSolid.svelte");
> const __vite_ssr_import_2__ = await __vite_ssr_import__("/node_modules/.pnpm/svelte-awesome-icons@0.2.11/node_modules/svelte-awesome-icons/VimeoVBrand.svelte");
> ...
> ```
> 
> I can't spot any incorrect configurations from the published package. https://www.npmjs.com/package/svelte-awesome-icons?activeTab=explore ~Maybe some plugin set by svelte-kit is doing that - transforming it early to CJS for SSR?~

### Steps To Reproduce

1. Go to project
2. Run tests `task unit_tests`

### Additional Information

Link to repo: https://gitlab.com/bookmarkey/gui

**Comment by shinokada** [comment]
Thanks for the report. I will fix it and let you know asap.

**Comment by shinokada** [comment]
Can you update to @0.2.16 and let me know.

**Comment by hmajid2301** [comment]
Updated; doesn't seem to make much of a difference https://gitlab.com/bookmarkey/gui/-/jobs/3708524352. But I wonder could it be something else affecting the run time ?

**Comment by shinokada** [comment]
Does uninstalling svelte-aweome-icons change the result?

**Comment by hmajid2301** [comment]
Seems to be an issue with vitest itself; https://github.com/vitest-dev/vitest/issues/1861#issuecomment-1415663535

This commit seems have fixed the issue: https://gitlab.com/bookmarkey/gui/-/merge_requests/75/diffs?commit_id=0eb1a6917cdd9b226937ecdda1571c29f3c4e3a7

Can close this issue.
