### ISSUE TITLE
[FEAT]: pro features

### ISSUE THREAD

**Issue by Dudek-AMS** [shinokada/svelte-awesome-icons#3]
### Description

Any plans to support font awesome pro icons?

**Comment by Dudek-AMS** [comment]
It's paid so people will need a license for using this.  But you could provide a build script to automatically create a up-to-date version of svelte-awesome-icons allowing also using the paid version if wanted. so people need to install npm font awesome paid as well and you're code is not affecting the licensing model of font awesome

**Comment by shinokada** [comment]
I created [a Bash script](https://github.com/shinokada/ssic) that converts SVG icons on a GitHub repo. 
It is OSS, so feel free to use it.

**Comment by Dudek-AMS** [comment]
thinks looks good, thank you
