### ISSUE TITLE
Source is misspelled Rource

### ISSUE THREAD

**Issue by Daschi1** [shinokada/svelte-awesome-icons#5]
### Describe the bug

On https://svelte-svg-icons.codewithshin.com/ for svelte-awesome-icons, Source is misspelled Rource. Since I could'nt find the source for the website, I thought I mention it here.

### Reproduction

Go to https://svelte-svg-icons.codewithshin.com/ and look at the info card for svelte-awesome-icons.

### Version and System Info

```shell
Website version as of 4th May 2024 11:48 PM (UTC)
```

**Comment by shinokada** [comment]
Fixed. Thanks.
